# Generated by Django 4.2.2 on 2023-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MoMo', 'Mobile_Money'), ('AITELE_MONEY', 'Aitel_Money'), ('BK', 'Bank_of_Kigali'), ('Equity', 'Equity_Bank'), ('VISA', 'VISA')], max_length=50),
        ),
    ]
